GET http://localhost:5000/todos 

####

POST http://localhost:5000/todo/new
Content-Type: application/json

{
    "title": "Title 1",
    "description" : "TEST",
    "enabled": true,
    "dubber": [{
        "name" : "aldi",
        "voice" : "Aldi"
    },
    {
        "name" : "budi",
        "voice" : "Budi"
    },
    {
        "name" : "cindy",
        "voice" : "Cindy"
    }]
}

###

DELETE http://localhost:5000/todo/delete/64993fabbccd9289e4e0af82

###

PUT http://localhost:5000/todo/update/64993fabbccd9289e4e0af82
Content-Type: application/json

{
    "title": "Title 1",
}

```
